# Generated by Django 3.2.5 on 2022-01-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_candidate_hr_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='hr_advantage',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1024, verbose_name='HR优势'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_disadvantage',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1024, verbose_name='HR顾虑和不足'),
        ),
    ]
