# Generated by Django 3.2.5 on 2022-01-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20220118_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='hr_advantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='HR优势'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_disadvantage',
            field=models.TextField(blank=True, max_length=1024, verbose_name='HR顾虑和不足'),
        ),
    ]
