# Generated by Django 3.2.5 on 2022-01-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20220118_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='hr_interview',
            new_name='hr_interviewer',
        ),
    ]
